[workspace]
resolver = "2"
members = ["lib/srv/desktop/rdp/rdpclient", "web/packages/teleport/src/ironrdp"]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
homepage = "https://github.com/gravitational/teleport"
repository = "https://github.com/gravitational/teleport"
publish = false

[profile.dev]
debug = 1
lto = "off"

[profile.release]
debug = 1
codegen-units = 1

[workspace.dependencies]
# Note: To use a local IronRDP repository as a crate (for example, ironrdp-cliprdr), define the dependency as follows:
# ironrdp-cliprdr = { path = "/path/to/local/IronRDP/crates/ironrdp-cliprdr" }
# TODO: move to master when https://github.com/Devolutions/IronRDP/pull/513 is merged
ironrdp-cliprdr = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-connector = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-displaycontrol = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-dvc = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-graphics = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-pdu = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-rdpdr = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-rdpsnd = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-session = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-svc = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
ironrdp-tls = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f", features = ["rustls" ] }
ironrdp-tokio = { git = "https://github.com/Devolutions/IronRDP", rev = "aac125cfc283182d614bcfcaae40865dfffb484f" }
